### ISSUE TITLE
How to run this project? Are there any graph visualization demo?

### ISSUE THREAD

**Issue by SetonLiang** [SlapDrone/wikigraph#1]

**Comment by SlapDrone** [comment]
Hey there, this was a rough experiment I started to see how possible it was to quickly build a hobby project from scratch with the assistance of GPT-4 back when it dropped. It's undocumented and honestly I don't remember what state I left it in. If it is useful to yourself or anyone else, I would be happy to do some more work on it when I have the time. Feel free to fork it and play around. If you get it working and develop it further feel free to let me know.
